# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name

    # Configuration for Shared module
    App\Shared\:
        resource: '../src/Shared'

    # Configuration for Driver module
    App\Driver\Application\:
        resource: '../src/Driver/Application'

    App\Driver\Domain\:
        resource: '../src/Driver/Domain'

    App\Driver\Infrastructure\:
        resource: '../src/Driver/Infrastructure'

    App\Driver\UI\:
        resource: '../src/Driver/UI'

    App\Driver\UI\Controller\:
        resource: '../src/Driver/UI/Controller'
        tags: ['controller.service_arguments']

    App\Driver\Application\MessageHandler\Command\:
        resource: '../src/Driver/Application/MessageHandler/Command/'
        autoconfigure: false
        tags: [ { name: messenger.message_handler, bus: command.bus } ]

    App\Driver\Application\MessageHandler\Query\:
        resource: '../src/Driver/Application/MessageHandler/Query/'
        autoconfigure: false
        tags: [ { name: messenger.message_handler, bus: query.bus } ]



    # Configuration for League module
    App\League\Application\:
        resource: '../src/League/Application'

    App\League\Domain\:
        resource: '../src/League/Domain'

    App\League\Infrastructure\:
        resource: '../src/League/Infrastructure'

    App\League\UI\:
        resource: '../src/League/UI'

    App\League\UI\Controller\:
        resource: '../src/League/UI/Controller'
        tags: [ 'controller.service_arguments' ]

    App\League\Application\MessageHandler\Command\:
        resource: '../src/League/Application/MessageHandler/Command/'
        autoconfigure: false
        tags: [ { name: messenger.message_handler, bus: command.bus } ]

    App\League\Application\MessageHandler\Query\:
        resource: '../src/League/Application/MessageHandler/Query/'
        autoconfigure: false
        tags: [ { name: messenger.message_handler, bus: query.bus } ]


    # Configuration for Race module
    App\Race\Application\:
        resource: '../src/Race/Application'

    App\Race\Domain\:
        resource: '../src/Race/Domain'

    App\Race\Infrastructure\:
        resource: '../src/Race/Infrastructure'

    App\Race\UI\:
        resource: '../src/Race/UI'

    App\Race\UI\Controller\:
        resource: '../src/Race/UI/Controller'
        tags: [ 'controller.service_arguments' ]

    App\Race\Application\MessageHandler\Command\:
        resource: '../src/Race/Application/MessageHandler/Command/'
        autoconfigure: false
        tags: [ { name: messenger.message_handler, bus: command.bus } ]

    App\Race\Application\MessageHandler\Query\:
        resource: '../src/Race/Application/MessageHandler/Query/'
        autoconfigure: false
        tags: [ { name: messenger.message_handler, bus: query.bus } ]



#    App\Services\:
#        resource: '../src/Services/'
#        tags: ['@doctrine.orm.default_entity_manager']
#    # add more service definitions when explicit configuration is needed
#    # please note that last definitions always *replace* previous ones